# Generated by Django 5.1 on 2024-08-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='list_1_row9',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='list_2_row9',
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
