# Generated by Django 5.1 on 2024-08-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0002_remove_questionbank_list_1_row9_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='exam_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='language',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='type_of_question',
            field=models.CharField(default='mcq1', max_length=100),
        ),
    ]
