# Generated by Django 5.1 on 2024-09-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0003_alter_questionbank_exam_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptiveTypeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_statement', models.TextField()),
                ('question_images', models.FileField(blank=True, null=True, upload_to='questions/images/')),
                ('question_documents', models.FileField(blank=True, null=True, upload_to='questions/documents/')),
                ('question_link', models.URLField(blank=True, null=True)),
                ('question_video', models.FileField(blank=True, null=True, upload_to='questions/videos/')),
                ('question_part_first', models.TextField(blank=True, null=True)),
                ('exam_name', models.CharField(max_length=255)),
                ('degree_of_difficulty', models.IntegerField()),
                ('subject_name', models.CharField(max_length=255)),
                ('area_name', models.CharField(max_length=255)),
                ('part_name', models.CharField(blank=True, max_length=255, null=True)),
                ('topic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
