# Generated by Django 5.1 on 2024-09-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0004_descriptivetypequestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descriptivetypequestion',
            old_name='question_part_first',
            new_name='other_text',
        ),
    ]
