# Generated by Django 5.1 on 2024-09-03 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0005_rename_question_part_first_descriptivetypequestion_other_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptivetypequestion',
            name='question_documents',
        ),
        migrations.RemoveField(
            model_name='descriptivetypequestion',
            name='question_images',
        ),
        migrations.CreateModel(
            name='QuestionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='questions/documents/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='question_bank.descriptivetypequestion')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='questions/images/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='question_bank.descriptivetypequestion')),
            ],
        ),
    ]
