# Generated by Django 5.1 on 2024-09-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0006_remove_descriptivetypequestion_question_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptivetypequestion',
            name='degree_of_difficulty',
        ),
        migrations.AddField(
            model_name='descriptivetypequestion',
            name='question_documents',
            field=models.FileField(blank=True, null=True, upload_to='questions/documents/'),
        ),
        migrations.AddField(
            model_name='descriptivetypequestion',
            name='question_images',
            field=models.FileField(blank=True, null=True, upload_to='questions/images/'),
        ),
    ]
