# Generated by Django 5.1 on 2024-09-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0007_remove_descriptivetypequestion_degree_of_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptivetypequestion',
            name='question_documents',
            field=models.FileField(blank=True, null=True, upload_to='descriptive_questions/documents/'),
        ),
        migrations.AlterField(
            model_name='descriptivetypequestion',
            name='question_images',
            field=models.FileField(blank=True, null=True, upload_to='descriptive_questions/images/'),
        ),
        migrations.AlterField(
            model_name='descriptivetypequestion',
            name='question_video',
            field=models.FileField(blank=True, null=True, upload_to='descriptive_questions/videos/'),
        ),
        migrations.AlterField(
            model_name='questiondocument',
            name='document',
            field=models.FileField(upload_to='QuestionImage/documents/'),
        ),
        migrations.AlterField(
            model_name='questionimage',
            name='image',
            field=models.ImageField(upload_to='QuestionImage/images/'),
        ),
    ]
