# Generated by Django 5.1 on 2024-09-05 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0009_area_examname_partname_subject_area_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='topic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_sub_type',
            field=models.CharField(choices=[('simple_type', 'Simple Type'), ('r_and_a_type', 'R & A Type'), ('list_type_1', 'List Type 1'), ('list_type_2', 'List Type 2'), ('true_false', 'True & False'), ('fill_in_the_blank', 'Fill in the Blank')], default='simple_type', max_length=100),
        ),
        migrations.CreateModel(
            name='TopicName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='question_bank.partname')),
            ],
        ),
    ]
