# Generated by Django 5.1 on 2024-09-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0010_questionbank_topic_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='question_sub_type',
            field=models.CharField(choices=[('simple_type', 'Simple Type'), ('r_and_a_type', 'R & A Type'), ('list_type_1', 'List Type 1'), ('list_type_2', 'List Type 2'), ('true_and_false_type', 'True & False'), ('fill_in_the_blank', 'Fill in the Blank')], default='simple_type', max_length=100),
        ),
    ]
