# Generated by Django 5.1 on 2024-09-09 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0012_alter_questionbank_question_sub_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_description', models.TextField()),
                ('details', models.TextField()),
                ('question_video', models.FileField(blank=True, null=True, upload_to='input_suggestion/videos/')),
                ('question_link', models.URLField(blank=True, null=True)),
                ('other_text', models.TextField(blank=True, null=True)),
                ('exam_name', models.CharField(max_length=255)),
                ('subject_name', models.CharField(max_length=255)),
                ('area_name', models.CharField(max_length=255)),
                ('part_name', models.CharField(blank=True, max_length=255, null=True)),
                ('topic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='questionimage',
            name='question',
        ),
        migrations.CreateModel(
            name='InputSuggestionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='input_suggestion/documents/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='question_bank.inputsuggestion')),
            ],
        ),
        migrations.CreateModel(
            name='InputSuggestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='input_suggestion/images/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='question_bank.inputsuggestion')),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionDocument',
        ),
        migrations.DeleteModel(
            name='DescriptiveTypeQuestion',
        ),
        migrations.DeleteModel(
            name='QuestionImage',
        ),
    ]
